# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'hackafront' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps'
  # Pods for hackafront

  target 'hackafront-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'hackafrontTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'hackafront-tvOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for hackafront-tvOS


  end

end
